### ISSUE TITLE
Lacks lit brimstone nearby

### ISSUE THREAD

**Issue by duarm** [BackupCup/hexed#3]
how does this mod work exactly? can't find a guide anywhere, thanks in advance

![image](https://github.com/BackupCup/hexed/assets/26150581/04ee6367-c59c-400e-9452-f83ba92e9400)

**Comment by BackupCup** [comment]
So, the altar, when placed, will show with particles where to place the candles. 2 of them have to be 1 block above others

No candles:
![image](https://github.com/BackupCup/hexed/assets/57048411/a2abdf71-a967-40e2-b1a1-dee02e6342b7)

With candles:
![image](https://github.com/BackupCup/hexed/assets/57048411/025ec739-85fb-4cbf-810e-02fca114ede0)
or
![image](https://github.com/BackupCup/hexed/assets/57048411/3e79c943-681a-457f-af64-04fa71ffda3c)

the altar will also show you with the same particles, which candles haven't been lit
