### ISSUE TITLE
Crashes due to some projectiles causing a NullPointerException

### ISSUE THREAD

**Issue by TheTrueYak** [BackupCup/hexed#6]
Sometimes when an arrow or other projectile is fired, the game can crash with a NullPointerException. This does not happen every time a projectile is fired, but does happen semi-frequently enough to disrupt gameplay, and also happens when tested in a bare instance. (Fabric API 0.92.1+1.20.1, Fabric Language Kotlin 1.11.0+kotlin.2.0.0, and Hexed 0.8.3 (dev)) Attached are 3 different crash logs, two from my main instance with arrows and another (modded) projectile type, and one from the bare instance.

[crash-2024-05-21_13.27.32-server.txt](https://github.com/BackupCup/hexed/files/15418009/crash-2024-05-21_13.27.32-server.txt)
[crash-2024-05-21_22.30.49-server.txt](https://github.com/BackupCup/hexed/files/15418013/crash-2024-05-21_22.30.49-server.txt)
[crash-2024-05-23_09.05.31-server.txt](https://github.com/BackupCup/hexed/files/15418024/crash-2024-05-23_09.05.31-server.txt)

**Comment by BackupCup** [comment]
This is a known issue that has already been fixed in the local dev. version.
