### ISSUE TITLE
Hexed causes the end biome added by other mods to not generate

### ISSUE THREAD

**Issue by Junnaturefox** [BackupCup/hexed#8]
I have tested the ends phantasm and eldritch end mods, and with the hexed mod installed at the same time, the new end biome add by them does not generate

**Comment by BackupCup** [comment]
Yes that is an issue with Biolith colliding with Terrablender

**Comment by Junnaturefox** [comment]
ends phantasm and eldritch end do not use terrablender as a dependency
why just close issues, because you guys don't want to fix this?

**Comment by BackupCup** [comment]
Both Eldrith end and Ends Phantasm don't even have worldgen compatability dependencies. They will at just as datapack, overriding any other custom worldgen. Having Biolith as included dependency in Hexed might cause neither of them to generate so for now, to not touch any worldgen related mods, i've removed Biolith as a dependency. This will be in the new release when it comes out.
